version: '3.9'

services:
  front:
    container_name: anki-front
    build:
      dockerfile: anki-Frontend/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./anki-Frontend
        target: ~/
      - type: volume
        source: front_node_modules
        target: ~/node_modules

volumes:
  front_node_modules:
