version: '3.9'

services:
  db:
    container_name: anki-database
    build:
      dockerfile: Database/Dockerfile
      context: .
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: anki-db-store
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  anki-db-store:
